// Full-stack PWA interop test (Wave 4 T4.4) — the capstone proof for the
// "native, wire-compatible with the PWA" claim.
//
// Feeds the committed PWA-produced fixtures (test/fixtures/*, generated by
// tests/interop-gen/gen-fixtures.test.ts via the PWA's real sender pipeline)
// through the FULL Dart receiver stack — FrameBuffer → Reassembler (backed by
// the real Rust FFI decoder through RustRaptorqFactory) → inflate → SHA-256 —
// and asserts the reassembled file is byte-identical to the PWA's original.
// Includes mid-broadcast join, frame loss, and tamper variants.
//
// Fixture on-disk formats:
//   data.frames / repair.frames  [u32BE len][wire frame bytes]… streams
//   meta.frame                   a single raw wire frame (META, re-broadcast)
//   original.bin                 the sender's input bytes
//   manifest.json                k / mtu / sessionId / fileSHA256
//
// Interop reconciliation with the landed codec (mirrors tests/interop.rs):
//   * Repair ESI: raptorq 2.0.1 changed the repair-packet ESI on the wire from
//     K' + i (RFC 6330 / the PWA's wasm v1.7.x) to kt + i. The crate's decoder
//     compensates by adding (K' - kt), so the PWA's raw repair frames (ESI =
//     K' + i) reconstruct garbage. The repair DATA is byte-identical (pinned by
//     pwa_repair_packets_as_encoded_expose_esi_regression) — only the 3-byte
//     ESI field differs, so this test normalizes it (with a recomputed CRC-32C)
//     before feeding, exactly as the crate interop test relabels packets.
//   * Loss/join fractions: the fixtures commit exactly 20 repair frames, so a
//     transfer of k symbols can survive at most ~20 lost source symbols. The
//     variants below drop/join the maximum the repair budget supports, the
//     hardest case that still decodes (the crate test does the same: it grows
//     the loss step until the budget absorbs it).
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:qr_transfer_core/codec/raptorq_bridge.dart';
import 'package:qr_transfer_core/protocol/crc32c.dart';
import 'package:qr_transfer_core/protocol/metadata.dart';
import 'package:qr_transfer_core/receiver/frames.dart';
import 'package:qr_transfer_core/receiver/reassembler.dart';
import 'package:test/test.dart';

/// A loaded fixture directory: the committed PWA wire bytes + manifest.
class FixtureSet {
  FixtureSet(this.name) {
    final dir = 'test/fixtures/$name';
    metaFrame = File('$dir/meta.frame').readAsBytesSync();
    dataFrames = _splitLengthPrefixed(
      File('$dir/data.frames').readAsBytesSync(),
    );
    repairFrames = _splitLengthPrefixed(
      File('$dir/repair.frames').readAsBytesSync(),
    );
    original = File('$dir/original.bin').readAsBytesSync();
    manifest =
        jsonDecode(utf8.decode(File('$dir/manifest.json').readAsBytesSync()))
            as Map<String, Object?>;
  }

  final String name;
  late final Uint8List metaFrame;
  late final List<Uint8List> dataFrames;
  late final List<Uint8List> repairFrames;
  late final Uint8List original;
  late final Map<String, Object?> manifest;

  int get k => manifest['k']! as int;
  int get mtu => manifest['mtu']! as int;

  /// Parsed transfer metadata — the document a receiver latches from the
  /// (re-broadcast) META frame.
  TransferMetadata get metadata => parseMetadataFrame(metaFrame);

  /// Repair frames with their packet ESI normalized from the PWA's K' + i to
  /// the crate v2.0.1 kt + i convention (CRC-32C recomputed). See the header
  /// comment — this is the one documented codec interop quirk.
  late final List<Uint8List> relabeledRepairFrames = _relabelRepairEsi();

  List<Uint8List> _relabelRepairEsi() {
    final offset = _packetEsi(repairFrames.first) - k;
    return [
      for (final frame in repairFrames)
        _rewritePacketEsi(frame, _packetEsi(frame) - offset),
    ];
  }
}

/// Splits a [u32BE len][frame bytes]… stream into full wire frames.
List<Uint8List> _splitLengthPrefixed(Uint8List bytes) {
  final frames = <Uint8List>[];
  final view = ByteData.sublistView(bytes);
  var offset = 0;
  while (offset < bytes.length) {
    final length = view.getUint32(offset, Endian.big);
    offset += 4;
    frames.add(Uint8List.sublistView(bytes, offset, offset + length));
    offset += length;
  }
  return frames;
}

/// The DATA frame payload length (30-byte wire header; blockLen at offset 22).
int _blockLen(Uint8List frame) =>
    ByteData.sublistView(frame).getUint32(22, Endian.little);

/// The RaptorQ packet ESI: payload bytes 1..=3, 24-bit big-endian (SBN is 0).
int _packetEsi(Uint8List frame) {
  final payload = 30;
  return (frame[payload + 1] << 16) |
      (frame[payload + 2] << 8) |
      frame[payload + 3];
}

/// Returns a copy of [frame] with its RaptorQ packet ESI rewritten and its
/// CRC-32C trailer recomputed, so the relabeled frame still passes the wire
/// gate and reaches the fountain decoder.
Uint8List _rewritePacketEsi(Uint8List frame, int esi) {
  final out = Uint8List.fromList(frame);
  final payload = 30;
  out[payload + 1] = (esi >> 16) & 0xff;
  out[payload + 2] = (esi >> 8) & 0xff;
  out[payload + 3] = esi & 0xff;
  final blockLen = _blockLen(out);
  final crc = crc32c(Uint8List.sublistView(out, 0, 30 + blockLen));
  ByteData.sublistView(out).setUint32(30 + blockLen, crc, Endian.little);
  return out;
}

/// One pipeline run: the real FrameBuffer plus the real Rust-backed
/// Reassembler, already started over the buffered symbols.
class ReassemblyRun {
  const ReassemblyRun({required this.buffer, required this.reassembler});

  final FrameBuffer buffer;
  final Reassembler reassembler;
}

/// Runs the full receiver pipeline for [fx]: feeds [frames] (after the
/// metadata re-broadcast) through the real FrameBuffer, starts a Reassembler
/// over the real FFI decoder, and — when the source symbols are not enough —
/// feeds the repair frames (ESI-normalized for the crate convention) and
/// calls feedMore.
Future<ReassemblyRun> _startReassembly(
  FixtureSet fx,
  List<Uint8List> frames, {
  bool feedRepair = true,
}) async {
  final buffer = FrameBuffer();
  buffer.feed(fx.metaFrame);
  for (final frame in frames) {
    buffer.feed(frame);
  }
  final reassembler = Reassembler(factory: RustRaptorqFactory(), mtu: fx.mtu);
  await reassembler.start(
    buffer.metadata!,
    buffer.symbols(),
    buffer.symbolEsiSet(),
  );
  if (feedRepair && !reassembler.isComplete) {
    for (final frame in fx.relabeledRepairFrames) {
      buffer.feed(frame);
    }
    reassembler.feedMore(buffer.symbols(), buffer.symbolEsiSet());
  }
  return ReassemblyRun(buffer: buffer, reassembler: reassembler);
}

/// Asserts [reassembler] produced a file byte-identical to the PWA original,
/// with the SHA-256 gate passed and the metadata's filename/mime preserved.
Future<void> _expectVerified(FixtureSet fx, Reassembler reassembler) async {
  final result = await reassembler.finish();
  expect(result.verified, isTrue);
  expect(result.bytes, equals(fx.original));
  expect(result.sha256, fx.manifest['fileSHA256']);
  expect(result.filename, fx.metadata.filename);
  expect(result.mime, fx.metadata.mime);
}

void main() {
  setUpAll(() => ensureRustLib());

  for (final name in ['random-1k', 'random-64k', 'text-256k']) {
    group(name, () {
      late final FixtureSet fx = FixtureSet(name);

      test(
        'full PWA broadcast reassembles byte-identical via the real FFI decoder',
        () async {
          // Given: the committed PWA frames for this fixture.
          // When: every DATA frame is fed through the real FrameBuffer.
          final buffer = FrameBuffer();
          buffer.feed(fx.metaFrame);
          for (final frame in fx.dataFrames) {
            buffer.feed(frame);
          }

          // Then: the buffer latched the session and holds exactly k symbols.
          expect(buffer.sessionId, fx.manifest['sessionId']);
          expect(buffer.k, fx.k);
          expect(buffer.uniqueSymbolCount, fx.k);

          final reassembler = Reassembler(
            factory: RustRaptorqFactory(),
            mtu: fx.mtu,
          );
          await reassembler.start(
            buffer.metadata!,
            buffer.symbols(),
            buffer.symbolEsiSet(),
          );
          expect(
            reassembler.isComplete,
            isTrue,
            reason: 'k source symbols must decode',
          );

          await _expectVerified(fx, reassembler);
        },
      );

      test(
        'mid-broadcast join recovers from the source tail + repair',
        () async {
          // Given: the receiver joins late and catches only the tail of the
          // source broadcast. The latest join the committed repair budget can
          // cover is keeping (k - repairCount + 1) source frames, so the tail
          // has exactly that many (the fountain property fills the gap).
          final joinKeep = max(0, fx.k - fx.repairFrames.length + 1);
          final tail = fx.dataFrames.sublist(fx.dataFrames.length - joinKeep);
          expect(
            tail.length,
            lessThan(fx.k),
            reason: 'a real mid-broadcast join',
          );

          // When: the tail and the repair stream are fed through the pipeline.
          final run = await _startReassembly(fx, tail);

          // Then: the file reassembles byte-identical despite the missed start.
          await _expectVerified(fx, run.reassembler);
        },
      );

      test('frame loss is recovered from the repair stream', () async {
        // Given: a deterministic uniform loss of source frames. The step is
        // chosen per fixture so survivors + the committed repair frames still
        // reach k distinct symbols (the fixtures commit exactly 20 repair
        // frames, which bounds the loss a fixture can survive).
        final step = max(2, (fx.k / fx.repairFrames.length).ceil());
        final survivors = <Uint8List>[
          for (var i = 0; i < fx.dataFrames.length; i++)
            if (i % step != 0) fx.dataFrames[i],
        ];
        expect(
          survivors.length,
          lessThan(fx.k),
          reason: 'a real loss happened',
        );

        // When: the surviving frames and the repair stream are fed.
        final run = await _startReassembly(fx, survivors);

        // Then: the fountain property rebuilds the file byte-identical.
        await _expectVerified(fx, run.reassembler);
      });

      test(
        'tampered frame never reaches verified:true with wrong bytes',
        () async {
          // Given: the first DATA frame's payload has one byte flipped and its
          // CRC-32C trailer recomputed, so the corruption passes the per-frame
          // wire gate and actually reaches the fountain decoder.
          final tampered = Uint8List.fromList(fx.dataFrames.first);
          tampered[30 + 100] ^= 0xff; // 30-byte header; byte 100 of the symbol.
          final blockLen = _blockLen(tampered);
          final crc = crc32c(Uint8List.sublistView(tampered, 0, 30 + blockLen));
          ByteData.sublistView(
            tampered,
          ).setUint32(30 + blockLen, crc, Endian.little);

          // When: the corrupted stream is reassembled through the real pipeline.
          final run = await _startReassembly(fx, [
            tampered,
            ...fx.dataFrames.sublist(1),
          ]);

          ReassemblyResult? result;
          Object? thrown;
          try {
            result = await run.reassembler.finish();
          } catch (error) {
            thrown = error;
          }

          // Then: the transfer is rejected by the whole-file SHA-256 gate, or —
          // if the decoder still produced a file — verified:true must imply the
          // bytes are the originals. A wrong file must never be verified.
          if (result != null) {
            expect(result.verified, isTrue);
            expect(result.bytes, equals(fx.original));
          } else {
            expect(thrown, isA<ReassemblyError>());
          }
        },
      );
    });
  }
}
