/// ZXing-C++ FFI ↔ PWA-fixture interop pin (Wave A2 integration).
///
/// Proves the new native decoder reassembles PWA-produced data byte-identical:
/// the committed PWA fixtures (test/fixtures/{random-1k,random-64k,text-256k},
/// generated by tests/interop-gen/gen-fixtures.test.ts via the PWA's real
/// sender pipeline) drive BOTH halves of the claim:
///
///  1. QR round-trip through the native ZXing-C++ FFI — the fixture's first
///     DATA frame is rebuilt as a real wire frame via `encodeFrame`, rasterized
///     to a tight 1-byte/px luma buffer, decoded with `decodeLuma`, and the
///     payload must come back byte-identical to the exact frame bytes.
///  2. Full receiver pipeline — the ZXing-decoded frame bytes are fed through
///     FrameBuffer → Reassembler (real `RustRaptorqFactory` FFI) and the final
///     file must be byte-identical to the fixture original AND SHA-256
///     verified (mirrors test/interop/interop_test.dart's flow; helpers are
///     replicated locally rather than importing a test file).
///
/// TDD: this file is written with a deliberately-broken first assertion
/// (`expect(decoded, isEmpty)`) to capture RED, then tightened to the
/// byte-exact assertion for GREEN. The FFI path itself (decodeLuma → the Rust
/// .so) is proven by A1/A2; this test pins the end-to-end reassembly.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:qr_transfer_core/codec/raptorq_bridge.dart'
    show RustRaptorqFactory, ensureRustLib;
import 'package:qr_transfer_core/codec/zxing_cpp_bridge.dart' show decodeLuma;
import 'package:qr_transfer_core/protocol/constants.dart' show typeData;
import 'package:qr_transfer_core/protocol/wire.dart'
    show Frame, decodeFrame, encodeFrame, generateSessionId;
import 'package:qr_transfer_core/qr/qr_encode.dart' show encodeQrBytes;
import 'package:qr_transfer_core/receiver/frames.dart' show FrameBuffer;
import 'package:qr_transfer_core/receiver/reassembler.dart' show Reassembler;
import 'package:test/test.dart';

/// A committed PWA fixture: the raw wire streams + the sender's original.
///
/// Local replica of interop_test.dart's FixtureSet (test files are not
/// imported); this subset covers the DATA/meta streams and the manifest the
/// ZXing-C++ interop pin needs.
class FixtureSet {
  FixtureSet(this.name) {
    final dir = 'test/fixtures/$name';
    metaFrame = File('$dir/meta.frame').readAsBytesSync();
    dataFrames = _splitLengthPrefixed(
      File('$dir/data.frames').readAsBytesSync(),
    );
    original = File('$dir/original.bin').readAsBytesSync();
    manifest =
        jsonDecode(utf8.decode(File('$dir/manifest.json').readAsBytesSync()))
            as Map<String, Object?>;
  }

  final String name;
  late final Uint8List metaFrame;
  late final List<Uint8List> dataFrames;
  late final Uint8List original;
  late final Map<String, Object?> manifest;

  int get k => manifest['k']! as int;
  int get mtu => manifest['mtu']! as int;
}

/// Splits a [u32BE len][frame bytes]… stream into full wire frames (the
/// on-disk `data.frames` layout).
List<Uint8List> _splitLengthPrefixed(Uint8List bytes) {
  final frames = <Uint8List>[];
  final view = ByteData.sublistView(bytes);
  var offset = 0;
  while (offset < bytes.length) {
    final length = view.getUint32(offset, Endian.big);
    offset += 4;
    frames.add(Uint8List.sublistView(bytes, offset, offset + length));
    offset += length;
  }
  return frames;
}

/// Rebuilds the fixture's first DATA frame as a real wire frame via the
/// protocol encoder (`encodeFrame`), reusing the committed frame's header
/// fields (esi / k / totalLen / flags) and payload — the "first-frame
/// pattern" from the fixture. When [freshSessionId] is true the rebuilt frame
/// gets a brand-new sessionId (the pure QR round-trip); when false it keeps
/// the fixture's sessionId so the decoded bytes can join the same FrameBuffer
/// session as the rest of the broadcast (the reassembly pin).
Uint8List rebuildFirstFrame(FixtureSet fx, {required bool freshSessionId}) {
  final first = decodeFrame(fx.dataFrames.first);
  return encodeFrame(
    Frame(
      type: typeData,
      sessionId: freshSessionId ? generateSessionId() : first.sessionId,
      esi: first.esi,
      k: first.k,
      totalLen: first.totalLen,
      flags: first.flags,
      payload: first.payload,
    ),
  );
}

/// Rasterizes [frame] into a tight, row-major luma buffer (dark = 0,
/// light = 255, 1 byte/px) at [ppm] pixels per module with a [quiet]-module
/// white quiet zone — the integer-scale rendering the broadcast sender uses,
/// so modules stay at whole-pixel scales.
({Uint8List luma, int px}) lumaImage(
  Uint8List frame, {
  int ppm = 4,
  int quiet = 4,
  int? version,
}) {
  final qr = encodeQrBytes(frame, version: version);
  final side = qr.size;
  final px = (side + 2 * quiet) * ppm;
  final luma = Uint8List(px * px);
  for (var y = 0; y < px; y++) {
    for (var x = 0; x < px; x++) {
      final mx = x ~/ ppm - quiet;
      final my = y ~/ ppm - quiet;
      final dark =
          mx >= 0 &&
          mx < side &&
          my >= 0 &&
          my < side &&
          qr.modules[my * side + mx] == 1;
      luma[y * px + x] = dark ? 0 : 255;
    }
  }
  return (luma: luma, px: px);
}

void main() {
  setUpAll(() => ensureRustLib());

  for (final name in ['random-1k', 'random-64k', 'text-256k']) {
    group(name, () {
      late final FixtureSet fx = FixtureSet(name);

      test('PWA fixture DATA frame round-trips byte-identical through the '
          'native ZXing-C++ FFI', () {
        // Given: the fixture's first DATA frame rebuilt via the protocol
        // encoder (a real wire frame, fresh sessionId for a pure QR pass).
        final frame = rebuildFirstFrame(fx, freshSessionId: true);

        // When: rasterized to tight luma and decoded by the native FFI.
        final image = lumaImage(frame);
        final decoded = decodeLuma(image.luma, image.px, image.px);

        // Then: the decoded payload equals the exact frame bytes —
        // byte-identical round trip through the native ZXing-C++.
        expect(decoded, hasLength(1));
        expect(decoded.single, equals(frame));
      });

      test('the ZXing-decoded frame reassembles the fixture byte-identical via '
          'FrameBuffer → Reassembler → SHA-256', () async {
        // Given: the fixture's first frame rebuilt keeping the fixture
        // sessionId, so its decoded bytes join the same broadcast session.
        final frame = rebuildFirstFrame(fx, freshSessionId: false);
        final image = lumaImage(frame);
        final decoded = decodeLuma(image.luma, image.px, image.px);
        expect(decoded, hasLength(1));
        expect(decoded.single, equals(frame));

        // When: the decoded frame (in place of the committed first frame)
        // plus the rest of the PWA broadcast run the real receiver stack.
        final buffer = FrameBuffer();
        buffer.feed(fx.metaFrame);
        for (var i = 0; i < fx.dataFrames.length; i++) {
          buffer.feed(i == 0 ? decoded.single : fx.dataFrames[i]);
        }
        expect(buffer.sessionId, fx.manifest['sessionId']);
        expect(buffer.uniqueSymbolCount, fx.k);

        final reassembler = Reassembler(
          factory: RustRaptorqFactory(),
          mtu: fx.mtu,
        );
        await reassembler.start(
          buffer.metadata!,
          buffer.symbols(),
          buffer.symbolEsiSet(),
        );
        expect(
          reassembler.isComplete,
          isTrue,
          reason: 'k source symbols must decode',
        );

        // Then: the file is byte-identical to the fixture original and the
        // whole-file SHA-256 gate passes.
        final result = await reassembler.finish();
        expect(result.verified, isTrue);
        expect(result.bytes, equals(fx.original));
        expect(result.sha256, fx.manifest['fileSHA256']);
      });
    });
  }
}
