//! RaptorQ FFI API for the Flutter app (Wave 2 T2.1).
//!
//! Wraps the `raptorq` 2.0.1 crate behind a `flutter_rust_bridge` surface that
//! mirrors the PWA codec wrapper (`src/codec/fountain/raptorq.ts`) semantics:
//!
//! * `RaptorqEncoder::with_defaults(data, mtu)` → `encode_source_packets()`
//!   yields the K systematic source packets; `encode_repair_packets(count)`
//!   yields `count` repair packets; `source_symbol_count()` is K and
//!   `symbol_size()` is the full serialized packet length (== mtu).
//! * `RaptorqDecoder::new(total_length, mtu)` is one-shot per transfer:
//!   `decode(packet)` returns the whole file once ≥ K distinct packets have
//!   arrived, `None` until then; after completion every further call returns
//!   `None` (tracked via the `done` flag).
//!
//! Wire format (verified against the 2.0.1 crate source — identical to 1.7):
//! byte 0 = source block number (u8), bytes 1-3 = encoding symbol id (24-bit
//! big-endian), then the symbol payload. Total serialized length == mtu.
//!
//! Sync by design: encode/decode are CPU-bound (~20 ms for 10 MB) and the
//! Flutter UI will run them in an isolate anyway; `#[frb(sync)]` keeps the Dart
//! surface simple (plain synchronous returns, no Futures). The bridge itself is
//! regenerated by `flutter_rust_bridge_codegen` — never hand-edit generated files.

/// Smallest MTU the crate's parameter search accepts without panicking
/// (`unreachable!` below 64, mirroring the PWA wrapper's guard).
const MIN_MTU: u16 = 64;
/// `max_packet_size` is a `u16`, so 65535 is the largest representable value.
const MAX_MTU: u16 = u16::MAX;

/// Encoder for one file. Produces the K systematic source packets plus an
/// unbounded supply of repair packets; the wire symbol size is mtu.
pub struct RaptorqEncoder {
    inner: raptorq::Encoder,
    /// K — the number of systematic source packets for the whole transfer.
    source_symbol_count: usize,
    /// Full serialized packet length, == mtu (PWA `metadata.symbolSize`).
    symbol_size: usize,
}

#[flutter_rust_bridge::frb(sync)]
impl RaptorqEncoder {
    /// Builds an encoder for `data` with the given MTU. The MTU must be in
    /// [64, 65535]; empty input is rejected (K would be 0).
    pub fn with_defaults(data: Vec<u8>, mtu: u16) -> Result<Self, String> {
        if !(MIN_MTU..=MAX_MTU).contains(&mtu) {
            return Err(format!("raptorq: mtu must be in [{MIN_MTU}, {MAX_MTU}], got {mtu}"));
        }
        if data.is_empty() {
            return Err("raptorq: cannot encode an empty file (K would be 0)".to_string());
        }
        let inner = raptorq::Encoder::with_defaults(&data, mtu);
        // encode(0) yields exactly the K source packets, so K falls out of the
        // systematic set (mirrors the PWA's `encode(0).length`).
        let source_symbol_count = inner.get_encoded_packets(0).len();
        Ok(Self { inner, source_symbol_count, symbol_size: mtu as usize })
    }

    /// K — the number of source symbols for this transfer (== ceil(len / (mtu-4))).
    pub fn source_symbol_count(&self) -> usize {
        self.source_symbol_count
    }

    /// The K systematic source packets, each `symbol_size` bytes long, in ESI order.
    pub fn encode_source_packets(&mut self) -> Vec<Vec<u8>> {
        self.inner.get_encoded_packets(0).iter().map(|p| p.serialize()).collect()
    }

    /// `count` repair packets (each `symbol_size` bytes, ESI ≥ K). `get_encoded_packets`
    /// returns the K source packets first, so they are sliced off and only the
    /// `count` repair packets are kept.
    pub fn encode_repair_packets(&mut self, count: usize) -> Vec<Vec<u8>> {
        self.inner
            .get_encoded_packets(count as u32)
            .into_iter()
            .skip(self.source_symbol_count)
            .map(|p| p.serialize())
            .collect()
    }

    /// Full serialized packet length, == mtu (PWA `metadata.symbolSize`).
    pub fn symbol_size(&self) -> usize {
        self.symbol_size
    }
}

/// One-shot decoder for a single transfer of `total_length` bytes. Returns the
/// recovered file once ≥ K distinct packets have been fed in; duplicates are
/// ignored by the underlying decoder.
pub struct RaptorqDecoder {
    inner: raptorq::Decoder,
    done: bool,
}

#[flutter_rust_bridge::frb(sync)]
impl RaptorqDecoder {
    /// Builds a one-shot decoder for a transfer of `total_length` bytes with
    /// the given MTU (must match the encoder's). MTU in [64, 65535];
    /// a zero-length transfer is rejected.
    pub fn new(total_length: u64, mtu: u16) -> Result<Self, String> {
        if !(MIN_MTU..=MAX_MTU).contains(&mtu) {
            return Err(format!("raptorq: mtu must be in [{MIN_MTU}, {MAX_MTU}], got {mtu}"));
        }
        if total_length == 0 {
            return Err("raptorq: cannot decode a zero-length transfer".to_string());
        }
        let config = raptorq::ObjectTransmissionInformation::with_defaults(total_length, mtu);
        Ok(Self { inner: raptorq::Decoder::new(config), done: false })
    }

    /// Feeds one serialized encoding packet. Returns the full decoded file once
    /// ≥ K distinct packets have arrived, `None` until then. After the file has
    /// been returned once, every later call returns `None` (one-shot decoder).
    pub fn decode(&mut self, packet: Vec<u8>) -> Option<Vec<u8>> {
        if self.done {
            return None;
        }
        // A valid packet is always ≥ the 4-byte header; the crate would panic
        // on a short slice, so guard the boundary.
        if packet.len() < 4 {
            return None;
        }
        let encoding_packet = raptorq::EncodingPacket::deserialize(&packet);
        match self.inner.decode(encoding_packet) {
            Some(result) => {
                self.done = true;
                Some(result)
            }
            None => None,
        }
    }
}

/// Decodes every QR in a grayscale luma frame (tight, row-major, 1 byte/px).
/// Returns the decoded payload bytes of every QR found; empty when none.
#[flutter_rust_bridge::frb(sync)]
pub fn decode_qr_barcodes(luma: Vec<u8>, width: u32, height: u32) -> Result<Vec<Vec<u8>>, String> {
    if luma.len() as u32 != width * height {
        return Err(format!("decode_qr_barcodes: luma {}B != {width}x{height}", luma.len()));
    }
    let view = zxingcpp::ImageView::from_slice(&luma, width, height, zxingcpp::ImageFormat::Lum)
        .map_err(|e| e.to_string())?;
    let reader = zxingcpp::read().formats(&[zxingcpp::BarcodeFormat::QRCode]);
    let barcodes = reader.from(&view).map_err(|e| e.to_string())?;
    Ok(barcodes.into_iter().map(|b| b.bytes()).collect())
}

#[cfg(test)]
mod tests {
    use super::RaptorqDecoder;
    use super::RaptorqEncoder;

    /// The MTU profiles exercised by the PWA soak matrix.
    const MTUS: [u16; 3] = [1028, 2052, 2564];
    /// File sizes spanning the PWA soak range, all single-source-block.
    const SIZES: [usize; 4] = [1024, 65_536, 262_144, 1_048_576];

    /// Deterministic pseudo-random data (LCG) — no external deps.
    fn pseudo_random(len: usize) -> Vec<u8> {
        let mut state: u64 = 0x1234_5678_9abc_def0;
        let mut out = vec![0u8; len];
        for byte in out.iter_mut() {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            *byte = (state >> 56) as u8;
        }
        out
    }

    /// K per the PWA contract: ceil(len / (mtu - 4)).
    fn expected_k(len: usize, mtu: u16) -> usize {
        len.div_ceil(mtu as usize - 4)
    }

    /// Reads the 24-bit big-endian ESI at packet bytes 1..=3.
    fn read_be24(packet: &[u8]) -> u32 {
        u32::from_be_bytes([0, packet[1], packet[2], packet[3]])
    }

    /// Feeds `packets` to `decoder`, returning the final decode result.
    fn feed_all(decoder: &mut RaptorqDecoder, packets: &[Vec<u8>]) -> Option<Vec<u8>> {
        packets.iter().fold(None, |acc, p| decoder.decode(p.clone()).or(acc))
    }

    #[test]
    fn round_trip_lossless_all_sizes_and_mtus() {
        for &len in &SIZES {
            for &mtu in &MTUS {
                let data = pseudo_random(len);
                let mut encoder = RaptorqEncoder::with_defaults(data.clone(), mtu)
                    .unwrap_or_else(|e| panic!("len={len} mtu={mtu}: {e}"));
                let k = encoder.source_symbol_count();
                assert_eq!(
                    k,
                    expected_k(len, mtu),
                    "K formula: len={len} mtu={mtu}"
                );
                assert_eq!(encoder.symbol_size(), mtu as usize, "symbol_size == mtu");

                let source_packets = encoder.encode_source_packets();
                assert_eq!(source_packets.len(), k, "source packet count == K");
                for packet in &source_packets {
                    assert_eq!(packet.len(), mtu as usize, "source packet length == mtu");
                }

                let mut decoder =
                    RaptorqDecoder::new(len as u64, mtu).unwrap_or_else(|e| panic!("{e}"));
                let decoded = feed_all(&mut decoder, &source_packets)
                    .expect("decodes with all K source packets");
                assert_eq!(decoded, data, "lossless round trip len={len} mtu={mtu}");
            }
        }
    }

    #[test]
    fn round_trip_with_10_and_20_percent_loss() {
        for &len in &SIZES {
            for &mtu in &MTUS {
                for &step in &[10usize, 5] {
                    let data = pseudo_random(len);
                    let mut encoder = RaptorqEncoder::with_defaults(data.clone(), mtu).unwrap();
                    let k = encoder.source_symbol_count();

                    // Deterministic loss: drop every `step`-th source packet.
                    let all = encoder.encode_source_packets();
                    let kept: Vec<Vec<u8>> = all
                        .iter()
                        .enumerate()
                        .filter(|(i, _)| i % step != 0)
                        .map(|(_, p)| p.clone())
                        .collect();
                    let dropped = k - kept.len();
                    assert!(dropped >= 1, "loss model must drop something");

                    // Replace the dropped packets with repair packets so the
                    // decoder still sees K distinct symbols.
                    let repairs = encoder.encode_repair_packets(dropped);
                    assert_eq!(repairs.len(), dropped, "exactly `dropped` repairs");

                    let mut decoder = RaptorqDecoder::new(len as u64, mtu).unwrap();
                    let mut to_feed = kept;
                    to_feed.extend(repairs);
                    let decoded = feed_all(&mut decoder, &to_feed)
                        .expect("decodes with K distinct after loss");
                    assert_eq!(
                        decoded, data,
                        "loss round trip len={len} mtu={mtu} step={step}"
                    );
                }
            }
        }
    }

    #[test]
    fn wire_format_header_and_esi() {
        let len = 65_536;
        let mtu = 1028;
        let data = pseudo_random(len);
        let mut encoder = RaptorqEncoder::with_defaults(data, mtu).unwrap();
        let k = encoder.source_symbol_count();

        let source_packets = encoder.encode_source_packets();
        for (i, packet) in source_packets.iter().take(8).enumerate() {
            assert_eq!(packet.len(), mtu as usize);
            assert_eq!(packet[0], 0, "SBN == 0 for the single source block");
            assert_eq!(
                read_be24(packet),
                i as u32,
                "source ESI == packet index for the systematic set"
            );
        }
        // ESIs of later source packets stay < K.
        for (i, packet) in source_packets.iter().enumerate().skip(k - 4).take(4) {
            assert!(read_be24(packet) < k as u32, "source ESI < K at index {i}");
        }

        let repairs = encoder.encode_repair_packets(5);
        assert_eq!(repairs.len(), 5, "encode_repair_packets(R) returns R packets");
        for packet in &repairs {
            assert_eq!(packet.len(), mtu as usize, "repair packet length == mtu");
            assert_eq!(packet[0], 0, "repair SBN == 0");
            assert!(read_be24(packet) >= k as u32, "repair ESI >= K");
        }
    }

    #[test]
    fn duplicate_packets_are_harmless() {
        let len = 65_536;
        let mtu = 1028;
        let data = pseudo_random(len);
        let mut encoder = RaptorqEncoder::with_defaults(data.clone(), mtu).unwrap();
        let source_packets = encoder.encode_source_packets();

        let mut decoder = RaptorqDecoder::new(len as u64, mtu).unwrap();
        // Feed every packet twice: the second copy must be ignored.
        // Keep the first Some — the decoder turns one-shot once complete.
        let mut decoded = None;
        for packet in &source_packets {
            decoded = decoded.or(decoder.decode(packet.clone()));
            decoded = decoded.or(decoder.decode(packet.clone()));
        }
        assert_eq!(decoded, Some(data), "duplicates must not break decode");
    }

    #[test]
    fn empty_input_and_mtu_guards() {
        let err = RaptorqEncoder::with_defaults(Vec::new(), 1028);
        assert!(err.is_err(), "empty input must be rejected");

        assert!(RaptorqEncoder::with_defaults(vec![1, 2, 3], 63).is_err(), "mtu 63 rejected");
        assert!(
            RaptorqEncoder::with_defaults(vec![1, 2, 3], 64).is_ok(),
            "mtu 64 accepted"
        );
        // 65536 is unrepresentable as u16 — the type enforces the upper bound;
        // the guard still rejects values at the boundary that u16 can express.
        assert!(
            RaptorqEncoder::with_defaults(vec![1, 2, 3], u16::MAX).is_ok(),
            "mtu 65535 accepted"
        );

        assert!(RaptorqDecoder::new(0, 1028).is_err(), "zero-length transfer rejected");
        assert!(RaptorqDecoder::new(10, 63).is_err(), "decoder mtu 63 rejected");
        assert!(RaptorqDecoder::new(10, 64).is_ok(), "decoder mtu 64 accepted");
    }

    #[test]
    fn decoder_is_one_shot() {
        let len = 65_536;
        let mtu = 1028;
        let data = pseudo_random(len);
        let mut encoder = RaptorqEncoder::with_defaults(data.clone(), mtu).unwrap();
        let source_packets = encoder.encode_source_packets();

        let mut decoder = RaptorqDecoder::new(len as u64, mtu).unwrap();
        let decoded = feed_all(&mut decoder, &source_packets);
        assert_eq!(decoded, Some(data));

        // After completion the decoder must refuse further packets.
        assert!(
            decoder.decode(source_packets[0].clone()).is_none(),
            "post-completion decode returns None"
        );
        assert!(decoder.decode(source_packets[1].clone()).is_none());
    }
}

#[cfg(test)]
mod zxing_tests {
    use super::decode_qr_barcodes;

    /// Light-luma gap (columns) between side-by-side QRs, >= the 4-module quiet
    /// zone QR needs.
    const GAP: u32 = 16;

    /// Deterministic 128-byte payload (LCG — same family as the RaptorQ tests).
    fn payload128() -> Vec<u8> {
        let mut state: u64 = 0xdead_beef_cafe_f00d;
        let mut out = vec![0u8; 128];
        for byte in out.iter_mut() {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            *byte = (state >> 56) as u8;
        }
        out
    }

    /// Rasterizes a QR for `payload` at `scale` px/module into a tight, row-major
    /// luma buffer (dark=0 / light=255). The writer's image is 1-byte Lum.
    fn qr_luma(payload: &[u8], scale: i32) -> (Vec<u8>, u32, u32) {
        let code = zxingcpp::create(zxingcpp::BarcodeFormat::QRCode)
            .from_slice(payload)
            .unwrap_or_else(|e| panic!("create QR: {e}"));
        let img = code
            .to_image_with(&zxingcpp::write().scale(scale))
            .unwrap_or_else(|e| panic!("rasterize QR: {e}"));
        (img.data(), img.width() as u32, img.height() as u32)
    }

    /// Lays luma images out side by side on a light (0xff) canvas of the common
    /// height, `gap` light columns between them, vertically centered.
    fn side_by_side(images: &[(Vec<u8>, u32, u32)], gap: u32) -> (Vec<u8>, u32, u32) {
        let height = images.iter().map(|(_, _, h)| *h).max().unwrap_or(0);
        let width: u32 = images.iter().map(|(_, w, _)| w).sum::<u32>() + gap * (images.len() as u32 - 1);
        let mut out = vec![0xffu8; width as usize * height as usize];
        let mut x = 0u32;
        for (data, w, h) in images {
            let y0 = (height - h) / 2;
            for (row, src) in data.chunks_exact(*w as usize).enumerate() {
                let dst = (y0 + row as u32) * width + x;
                out[dst as usize..dst as usize + src.len()].copy_from_slice(src);
            }
            x += w + gap;
        }
        (out, width, height)
    }

    #[test]
    fn decode_qr_barcodes_round_trips_byte_exact() {
        let payload = payload128();
        let (luma, w, h) = qr_luma(&payload, 4);
        let decoded = decode_qr_barcodes(luma, w, h).unwrap_or_else(|e| panic!("decode: {e}"));
        assert_eq!(decoded.len(), 1, "exactly one QR");
        assert_eq!(decoded[0], payload, "byte-exact round trip");
    }

    #[test]
    fn decode_all_qrs_in_one_frame() {
        let a = payload128();
        let b = vec![0x5a; 64];
        let (la, wa, ha) = qr_luma(&a, 4);
        let (lb, wb, _) = qr_luma(&b, 4);
        let (luma, w, h) = side_by_side(&[(la, wa, ha), (lb, wb, ha)], GAP);
        let decoded = decode_qr_barcodes(luma, w, h).unwrap_or_else(|e| panic!("decode: {e}"));
        assert_eq!(decoded.len(), 2, "two QRs in one frame");
        let set: std::collections::HashSet<Vec<u8>> = decoded.into_iter().collect();
        assert!(set.contains(&a), "payload A present");
        assert!(set.contains(&b), "payload B present");
    }

    #[test]
    fn decode_empty_when_no_qr() {
        let luma = vec![0xffu8; 64 * 64];
        let decoded = decode_qr_barcodes(luma, 64, 64).unwrap_or_else(|e| panic!("decode: {e}"));
        assert!(decoded.is_empty(), "uniform grey frame yields no QR");
    }

    #[test]
    fn decode_rejects_dimension_mismatch() {
        let err = decode_qr_barcodes(vec![0u8; 99], 10, 10).expect_err("len 99 != 10x10");
        assert!(err.contains("99"), "error mentions the mismatched length");
    }
}
