#!/usr/bin/env bash
# Builds the native RaptorQ codec for Android and drops it into
# `android/app/src/main/jniLibs` so `flutter build apk` bundles it.
#
# WHY arm64-v8a ONLY: raptorq 2.0.1's NEON path requires unstable stdarch
# intrinsics on 32-bit ARM (it compiles for aarch64, not armv7). 32-bit ARM
# phones are a tiny legacy slice; the APK is restricted to arm64 accordingly
# (see the `ndk { abiFilters }` block in android/app/build.gradle.kts).
#
# The `android/` directory is gitignored (regenerated by `flutter create`), so
# this script is the committed source of truth for the codec .so. Run it after
# any fresh clone / `flutter create`, and after any change to `rust/src/api.rs`.
#
# Prerequisites: Rust toolchain (rustup), cargo-ndk (installed automatically),
# and the Android NDK at $ANDROID_NDK_ROOT (or auto-detected under $ANDROID_HOME).
#
# Usage:
#   flutter_app/scripts/build-android-so.sh          # release (default)
#   PROFILE=debug flutter_app/scripts/build-android-so.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUST_DIR="$ROOT/rust"
JNILIBS_DIR="$ROOT/android/app/src/main/jniLibs"
ABI="${ABI:-arm64-v8a}"            # android ABI directory name
TARGET="aarch64-linux-android"     # rust triple for that ABI
PROFILE="${PROFILE:-release}"

# --- NDK detection ----------------------------------------------------------
if [[ -z "${ANDROID_NDK_ROOT:-}" && -n "${ANDROID_HOME:-}" ]]; then
  ANDROID_NDK_ROOT="$(ls -d "$ANDROID_HOME"/ndk/* 2>/dev/null | tail -1 || true)"
fi
if [[ -z "${ANDROID_NDK_ROOT:-}" ]]; then
  # Common default: ~/Android/Sdk/ndk/<version>
  for sdk in "$HOME/Android/Sdk" "$HOME/Library/Android/sdk"; do
    if [[ -d "$sdk/ndk" ]]; then
      ANDROID_NDK_ROOT="$(ls -d "$sdk"/ndk/* 2>/dev/null | tail -1 || true)"
      break
    fi
  done
fi
export ANDROID_NDK_ROOT
if [[ -z "${ANDROID_NDK_ROOT:-}" || ! -d "$ANDROID_NDK_ROOT" ]]; then
  echo "error: Android NDK not found — set ANDROID_NDK_ROOT (or ANDROID_HOME with an ndk/ dir)" >&2
  exit 1
fi

# --- toolchain --------------------------------------------------------------
rustup target add "$TARGET" >/dev/null 2>&1 || true
command -v cargo-ndk >/dev/null 2>&1 || cargo install cargo-ndk --locked

# --- build ------------------------------------------------------------------
mkdir -p "$JNILIBS_DIR/$ABI"
(
  cd "$RUST_DIR"
  cargo ndk -t "$ABI" -o "$JNILIBS_DIR" build --"$PROFILE"
)
echo "built: $JNILIBS_DIR/$ABI/libqr_transfer_rust.so"
