/**
 * Flutter → PWA wire-compatibility proof (Wave 6, T6.2).
 *
 * The forward direction (PWA→Flutter) is already proven by
 * `flutter_app/rust/tests/interop.rs` + `flutter_app/core/test/interop/`
 * (the crate decodes the PWA wasm's fixtures byte-identical). This test closes
 * the reverse direction: it feeds packets produced by the NATIVE crate
 * (raptorq 2.0.1, `flutter_app/rust`) into the PWA's wasm Decoder (raptorq
 * 1.7.24) and asserts a byte-identical reassembly of `payload.bin`.
 *
 * The native packets come from the committed fixture
 * `flutter_app/core/test/fixtures/random-64k/native.data.frames`, generated by:
 *
 *     cd flutter_app/rust && cargo run --bin dump_packets
 *
 * That binary reads the same `payload.bin` + `manifest.json` the PWA encoder
 * used, runs the crate `Encoder::with_defaults(payload, mtu)`, and writes the K
 * systematic source packets in the fixture convention `[u32 BE len][packet]…`,
 * where each packet is the raw RaptorQ wire packet
 * `[SBN u8][ESI BE24] + symbol` (length == mtu) — exactly what the wasm
 * `Decoder.decode(packet)` consumes.
 *
 * The fixture is committed, so the vitest suite needs no cargo toolchain; only
 * regenerating it does.
 */
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import init, { Decoder } from 'raptorq/raptorq.js'

/** The committed random-64k fixture directory. */
const FIXTURE_DIR = fileURLToPath(
  new URL('../../flutter_app/core/test/fixtures/random-64k/', import.meta.url),
)

/** Wire parameters the decoder must be configured with. */
interface Manifest {
  readonly k: number
  readonly mtu: number
  readonly compressedSize: number
}

function requireInt(manifest: Record<string, unknown>, key: string): number {
  const value = manifest[key]
  if (typeof value !== 'number' || !Number.isInteger(value)) {
    throw new Error(`manifest.${key} is not an integer: ${String(value)}`)
  }
  return value
}

function loadManifest(path: string): Manifest {
  const raw = JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>
  return {
    k: requireInt(raw, 'k'),
    mtu: requireInt(raw, 'mtu'),
    compressedSize: requireInt(raw, 'compressedSize'),
  }
}

/** Split the on-disk [u32 BE len][packet bytes]… stream back into packets. */
function splitLengthPrefixed(bytes: Uint8Array): Uint8Array[] {
  const packets: Uint8Array[] = []
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  let offset = 0
  while (offset < bytes.length) {
    const length = view.getUint32(offset, false)
    offset += 4
    packets.push(bytes.slice(offset, offset + length))
    offset += length
  }
  return packets
}

/** The 24-bit big-endian ESI at packet bytes 1..=3 (byte 0 is the SBN). */
function readBe24(packet: Uint8Array): number {
  const [, b1, b2, b3] = packet
  if (b1 === undefined || b2 === undefined || b3 === undefined) {
    throw new Error(`packet too short for an ESI (len ${packet.length})`)
  }
  return (b1 << 16) | (b2 << 8) | b3
}

describe('reverse interop (Flutter → PWA)', () => {
  it('decodes native crate source packets byte-identical in the PWA wasm', async () => {
    // Given — the native dump produced by `cargo run --bin dump_packets`
    // (flutter_app/rust), plus the same payload and wire parameters the PWA
    // encoder used.
    const framesPath = join(FIXTURE_DIR, 'native.data.frames')
    if (!existsSync(framesPath)) {
      throw new Error(
        `missing ${framesPath} — run "cargo run --bin dump_packets" in flutter_app/rust first`,
      )
    }
    const manifest = loadManifest(join(FIXTURE_DIR, 'manifest.json'))
    const payload = readFileSync(join(FIXTURE_DIR, 'payload.bin'))

    const packets = splitLengthPrefixed(readFileSync(framesPath))

    // Then — wire structure: one source block, full-size packets, ESI 0..9.
    expect(packets.length).toBe(manifest.k)
    const firstPacket = packets[0]
    expect(firstPacket).toBeDefined()
    expect(firstPacket?.[0]).toBe(0x00) // SBN == 0 (single source block)
    for (const packet of packets) {
      expect(packet.length).toBe(manifest.mtu)
    }
    expect(packets.slice(0, 10).map(readBe24)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

    // When — the REAL PWA wasm decoder is initialized from the committed wasm
    // bytes (fetch(file://) fails under Node) and fed each native packet.
    const { createRequire } = await import('node:module')
    const wasmBytes = readFileSync(
      createRequire(import.meta.url).resolve('raptorq/raptorq_bg.wasm'),
    )
    await init(wasmBytes)
    const decoder = Decoder.with_defaults(BigInt(manifest.compressedSize), manifest.mtu)
    try {
      let decoded: Uint8Array | undefined
      for (const packet of packets) {
        decoded = decoder.decode(packet)
        if (decoded !== undefined) {
          break
        }
      }

      // Then — the wasm reassembles the exact bytes the PWA originally encoded.
      if (decoded === undefined) {
        throw new Error('wasm decoder never completed after feeding all K source packets')
      }
      expect(decoded.length).toBe(manifest.compressedSize)
      expect([...decoded]).toEqual([...payload])
    } finally {
      decoder.free()
    }
  })
})
